### PR TITLE
Upgrade `groovy-xml` from 3.0.9 to 4.0.6

### PR DESCRIPTION
**Pull request by basil**
With this PR and https://github.com/jenkinsci/jenkins/pull/7293, compiling Jenkins on Java 19 is successful and `war/target/classes/META-INF/licenses.html` looks the same as before this PR.

Without this PR but with https://github.com/jenkinsci/jenkins/pull/7293, compiling Jenkins on Java 19 results in

```
[ERROR] Failed to execute goal com.cloudbees:maven-license-plugin:1.10:process (default) on project jenkins-war: Execution default of goal com.cloudbees:maven-license-plugin:1.10:process failed: startup failed:
[ERROR] General error during conversion: Unsupported class file major version 63
[ERROR] 
[ERROR] java.lang.IllegalArgumentException: Unsupported class file major version 63
[ERROR]         at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:199)
[ERROR]         at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:180)
[ERROR]         at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
[ERROR]         at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:287)
[ERROR]         at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
[ERROR]         at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
[ERROR]         at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
[ERROR]         at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
[ERROR]         at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
[ERROR]         at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClassNullable(AsmReferenceResolver.java:57)
[ERROR]         at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClass(AsmReferenceResolver.java:44)
[ERROR]         at org.codehaus.groovy.ast.decompiled.ClassSignatureParser.configureClass(ClassSignatureParser.java:42)
[ERROR]         at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.lazyInitSupers(DecompiledClassNode.java:185)
[ERROR]         at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.isUsingGenerics(DecompiledClassNode.java:86)
[ERROR]         at org.codehaus.groovy.ast.tools.GenericsUtils.nonGeneric(GenericsUtils.java:275)
[ERROR]         at org.codehaus.groovy.ast.decompiled.MemberSignatureParser.createFieldNode(MemberSignatureParser.java:176)
[ERROR]         at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.lambda$createFieldNode$0(DecompiledClassNode.java:220)
[ERROR]         at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.createFieldNode(DecompiledClassNode.java:226)
[ERROR]         at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.lazyInitMembers(DecompiledClassNode.java:210)
[ERROR]         at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.getDeclaredMethods(DecompiledClassNode.java:122)
[ERROR]         at org.codehaus.groovy.ast.ClassNode.tryFindPossibleMethod(ClassNode.java:1283)
[ERROR]         at org.codehaus.groovy.control.StaticImportVisitor.transformMethodCallExpression(StaticImportVisitor.java:251)
[ERROR]         at org.codehaus.groovy.control.StaticImportVisitor.transform(StaticImportVisitor.java:133)
[ERROR]         at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitExpressionStatement(ClassCodeExpressionTransformer.java:108)
[ERROR]         at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
[ERROR]         at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:138)
[ERROR]         at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:111)
[ERROR]         at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitConstructorOrMethod(ClassCodeExpressionTransformer.java:66)
[ERROR]         at org.codehaus.groovy.control.StaticImportVisitor.visitConstructorOrMethod(StaticImportVisitor.java:108)
[ERROR]         at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructor(ClassCodeVisitorSupport.java:101)
[ERROR]         at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1089)
[ERROR]         at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:52)
[ERROR]         at org.codehaus.groovy.control.CompilationUnit.lambda$addPhaseOperations$3(CompilationUnit.java:209)
[ERROR]         at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:942)
[ERROR]         at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:671)
[ERROR]         at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:635)
[ERROR]         at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
[ERROR]         at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
[ERROR]         at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
[ERROR]         at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
[ERROR]         at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
[ERROR]         at groovy.lang.GroovyShell.parseClass(GroovyShell.java:526)
[ERROR]         at groovy.lang.GroovyShell.parse(GroovyShell.java:538)
[ERROR]         at groovy.lang.GroovyShell.parse(GroovyShell.java:547)
[ERROR]         at com.cloudbees.maven.license.ProcessMojo.parseScripts(ProcessMojo.java:254)
[ERROR]         at com.cloudbees.maven.license.ProcessMojo.execute(ProcessMojo.java:139)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[ERROR]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

CC @jglick

### CODE REVIEW

**Review by jglick — APPROVED** [review]
Let me see if I can still release…

**Comment by jglick** [comment]
Need to export `JAVA_HOME` with this version of `maven-javadoc-plugin` evidently. Next problem:

```
[INFO] Executing: /bin/sh -c cd …/maven-license-plugin && git commit --verbose -F /tmp/maven-scm-304286607.commit pom.xml
[INFO] Working directory: …/maven-license-plugin
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.669 s
[INFO] Finished at: 2022-10-21T20:58:26-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.1:prepare (default-cli) on project maven-license-plugin: Unable to commit files
[ERROR] Provider message:
[ERROR] The git-commit command failed.
[ERROR] Command output:
[ERROR] -> [Help 1]
```

Ancient versions of plugins…

**Comment by jglick** [comment]
Next:

```
javadoc: error - No source files for package reference
```

How I loathe `maven-release-plugin`…

**Comment by jglick** [comment]
That was on JDK 11. Using JDK 8, Javadoc at least runs…but then complains about `unknown tag`.

**Comment by jglick** [comment]
I think I managed to release 1.12.

**Comment by basil** [comment]
Thank you!

**Pull request merged**
